### ISSUE TITLE
赞不起来拉！

### ISSUE THREAD

**Issue by 54853315** [zeruniverse/QzoneLiker#1]
HELLO! 我是V2EXer！
看到你的帖子很喜欢，已经全线Star！

现在用不起这个python，无报错，登录正常（手机APP有显示电脑登录），但是一条都没赞呢！ 
好想变成点赞小王子啊！！！

qliker.log
 是空的

log.log：

Tue, 18 Aug 2015 20:02:59  QLiker.py[line:61] CRITICAL 正在获取登陆页面
Tue, 18 Aug 2015 20:03:01  QLiker.py[line:70] INFO [1] Get QRCode Picture Success.
Tue, 18 Aug 2015 20:03:34  QLiker.py[line:83] CRITICAL 二维码已扫描，正在登陆
Tue, 18 Aug 2015 20:07:33  QLiker.py[line:61] CRITICAL 正在获取登陆页面
Tue, 18 Aug 2015 20:07:34  QLiker.py[line:70] INFO [1] Get QRCode Picture Success.
Tue, 18 Aug 2015 20:07:43  QLiker.py[line:83] CRITICAL 二维码已扫描，正在登陆

命令行：
KONAKONAs-MAC:QzoneLiker mac$ python QLiker.py >qliker.log&
[1] 69709
KONAKONAs-MAC:QzoneLiker mac$

**Comment by zeruniverse** [comment]
你试试电脑上登录qzone.qq.com

**Comment by zeruniverse** [comment]
如果你频率过高qq会封你的qq空间网页版，请求直接返回403

**Comment by 54853315** [comment]
电脑可以进入qzone，其实一个都没赞……应该属于没频率啊……

**Comment by zeruniverse** [comment]
那你得debug一下了。把msg handler函数第一步获取到的html输出到log文件
**logging.critical(str(html))**,然后看看那个html里面有没有需要的信息

**Comment by zeruniverse** [comment]
Closed due to no response for a long time
