### ISSUE TITLE
运行异常

### ISSUE THREAD

**Issue by xborner** [zeruniverse/QzoneLiker#12]
作者你好，请问下登录时发生这种问题是怎么回事啊。查看log.log：
Wed, 05 Apr 2017 11:10:12  QLiker.py[line:61] CRITICAL 正在获取登陆页面
Wed, 05 Apr 2017 11:10:14  QLiker.py[line:70] INFO [1] Get QRCode Picture Success.
Wed, 05 Apr 2017 11:10:15  QLiker.py[line:184] CRITICAL list index out of range
而在qlike.log没有记录

**Comment by zeruniverse** [comment]
二维码扫描失败

**Comment by suninsky** [comment]
总是二维码过期无效，重新生成结果依旧

**Comment by xborner** [comment]
@zeruniverse手机上显示扫码成功了，服务端似乎检测不到

**Comment by zeruniverse** [comment]
可能是tx把你ip屏蔽了 试试本地电脑。我的digitalocean服务器好像也挂了

**Comment by zeruniverse** [comment]
@xborner @suninsky 
问题由TX更新协议引起 现已修复，欢迎试用

**Comment by xborner** [comment]
每隔两天就会挂掉。error fail to find any feeds
需要手动重启，算是正常情况吗，还是说刷新的频率过快，使用默认配置的。
