### ISSUE TITLE
老大 这个东西还能用不能啊 ？

### ISSUE THREAD

**Issue by wehaha** [zeruniverse/QzoneLiker#13]
试了试 一直登陆 out   这么害的东西为不维护了呢  相比网页的那个 这个还是比较简单的

**Comment by zeruniverse** [comment]
Sorry for the late reply. I'll fix it when I have time

**Comment by zeruniverse** [comment]
已修复，欢迎试用

**Comment by wehaha** [comment]
还是不行。。。。

2017-05-31 14:22 GMT+08:00 Jeffery Zhao <notifications@github.com>:

**Comment by zeruniverse** [comment]
请先用网页版登陆一次后再跑程序
