### ISSUE TITLE
两个QQ只能成功运行一个

### ISSUE THREAD

**Issue by Liuwt1997** [zeruniverse/QzoneLiker#14]
两个qq，一个成功运行没问题，另一个登录成功但总是报错。试了两天，网页版空间登录后运行程序还是无效。
Tue, 27 Jun 2017 10:12:47 qqbot.py[line:249] ERROR Fail to find any feeds

**Comment by zeruniverse** [comment]
Please run the code below with the QQ account that doesn't work (remove `.txt` in the file name first).
[QLiker.py.txt](https://github.com/zeruniverse/QzoneLiker/files/1104016/QLiker.py.txt)

And paste the **console output** to the issue

**Comment by Liuwt1997** [comment]
Tue, 27 Jun 2017 10:34:05  QLiker.py[line:68] CRITICAL 正在获取登陆页面
Tue, 27 Jun 2017 10:34:08  QLiker.py[line:79] INFO [1] Get QRCode Picture Success.
Tue, 27 Jun 2017 10:34:18  QLiker.py[line:93] CRITICAL 二维码已扫描，正在登陆
Tue, 27 Jun 2017 10:34:19  QLiker.py[line:106] CRITICAL Successfully Login, Username: Liuwt1997
Tue, 27 Jun 2017 10:34:19  QLiker.py[line:209] ERROR Fail to find any feeds
Tue, 27 Jun 2017 10:34:20  QLiker.py[line:209] ERROR Fail to find any feeds
Tue, 27 Jun 2017 10:34:20  QLiker.py[line:209] ERROR Fail to find any feeds
Tue, 27 Jun 2017 10:34:21  QLiker.py[line:209] ERROR Fail to find any feeds
Tue, 27 Jun 2017 10:34:21  QLiker.py[line:209] ERROR Fail to find any feeds
Tue, 27 Jun 2017 10:34:22  QLiker.py[line:209] ERROR Fail to find any feeds

**Comment by zeruniverse** [comment]
这是log，我要你的终端输出。 你不要nohup 直接 python QQLiker.py

你终端里面会输出你错误时候的html

要用我发给你的那份代码

**Comment by Liuwt1997** [comment]
第一次提issue，不好意思
[output.txt](https://github.com/zeruniverse/QzoneLiker/files/1104065/output.txt)

**Comment by zeruniverse** [comment]
请尝试一下这份代码。
[QLiker.py.txt](https://github.com/zeruniverse/QzoneLiker/files/1104230/QLiker.py.txt)

如果还不行请再提交终端输出

错误原因为抓取的页面为“与我相关”，非默认“全部动态”。
错误无法用我的账号重现

**Comment by zeruniverse** [comment]
@Liuwt1997
可以用了么？

**Comment by Liuwt1997** [comment]
成功运行，Thanks

**Comment by zeruniverse** [comment]
Thanks for the response!
