### ISSUE TITLE
有考虑增加账号密码登录功能吗

### ISSUE THREAD

**Issue by FelixZhu** [zeruniverse/QzoneLiker#3]
有考虑增加账号密码登录功能吗

**Comment by zeruniverse** [comment]
账号密码登录需要识别验证码，而且不容易被用户信任。

如果你非要实现，这里有现成的：https://github.com/xqin/PiWebQQ

**Comment by zeruniverse** [comment]
腾讯已取消对WEBQQ的账号密码方式认证。估计空间以后的趋势也是只能采用二维码登录

故不再考虑在本项目中添加账号密码登陆功能

此ISSUE关闭
