### ISSUE TITLE
讲真的

### ISSUE THREAD

**Issue by Zero287** [zeruniverse/QzoneLiker#8]
兄弟你弄得那个httpclient简直了，直接把人给绕晕了，代码看上去各种乱

**Comment by zeruniverse** [comment]
httpclient不是我写的 license里面给了credit。

**Comment by Zero287** [comment]
javescript那一步你的cookies信息从哪里获取的？我请求时总是出现提交参数错误，

**Comment by zeruniverse** [comment]
httpclient里面

**Comment by QiLiuXianSheng** [comment]
为什么的老是过一段就登录失效了。。

**Comment by zeruniverse** [comment]
README里面有写，这是TX的问题
