### ISSUE TITLE
关于使用

### ISSUE THREAD

**Issue by maxskywalker** [zeruniverse/QzoneLiker#9]
你好:
        想请教下如何使用这个点赞程序。
下载后使用Python2运行QLiker.py ----这个是在cmd中，python QLiker.py吗？我感觉输入后好像卡死了。

nohup python2 QLiker.py >qliker.log&  ----这是不是需要下载nohup库？
 
感谢指导了，谢谢。

**Comment by zeruniverse** [comment]
nohup 是后台挂起的意思。在你关掉terminal后继续运行。所有linux系统都有这个命令

这个程序是一直循环的，而且不输出到terminal 所以直接跑像卡死的样子

**Comment by maxskywalker** [comment]
感谢作者的热心解答：
![2016-12-05_160408](https://cloud.githubusercontent.com/assets/20500415/20877608/c83f7940-bb04-11e6-9167-973762afe1fe.png)
为什么在我的linux系统中运行下述两条命令均无法成功？还望大神指点下迷津，谢谢？
nohup python2 QLiker.py >qliker.log&
nohup python QLiker.py >qliker.log&

**Comment by zeruniverse** [comment]
你这个已经运行成功了。它就是这样的。[3] 3535的意思是后台自动在跑这个程序，pid是：3535，你在terminal上干别的不会中断这个程序。

出现[3] 3535后你只需要打开文件夹下的v.jpg扫描二维码登录即可。log记录在log.log里

**Comment by maxskywalker** [comment]
太感谢您的热心解答，我就是一小白，跟大神一起学习进步
